language:
    - objective-c

before_install:
    - brew update

env:
    - BUILD_TYPE=Debug BUILD32=ON
    - BUILD_TYPE=Release BUILD32=ON
    - BUILD_TYPE=Debug BUILD32=OFF
    - BUILD_TYPE=Release BUILD32=OFF

install:
    - brew install python3
    - brew install boost

script:
    - cmake -H. -B_builds -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_VERBOSE_MAKEFILE=ON -DUSE_LIBCXX=ON -DBUILD32=${BUILD32}
    - cmake --build _builds
    - cd _builds
    - ctest -VV -C ${BUILD_TYPE}
