language:
    - cpp

compiler:
    - gcc
    - clang

env:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

install:
    - sudo apt-get install cmake

script:
    - cmake -H. -B_builds -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
    - cmake --build _builds
    - cd _builds
    - ctest -VV -C ${BUILD_TYPE}
