language:
    - objective-c

before_install:
    - brew update

env:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

install:
    - brew install python3
    - brew install boost

script:
    - cmake -H. -B_builds -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_VERBOSE_MAKEFILE=ON -DUSE_LIBCXX=ON
    - cmake --build _builds
    - cd _builds
    - ctest -VV -C ${BUILD_TYPE}
